// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftjuxazugtlrhhkztemh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0anV4YXp1Z3Rscmhoa3p0ZW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzcxNjEsImV4cCI6MjA2MDMxMzE2MX0.JGc4666_9xULIF0_1hCupA8i6myOP0CY6skVPBbTVhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);